version: "3"

services:
  staking-web:
    image: staking-web
    build:
        context: .
        dockerfile: Dockerfile-prod
    restart: always
    volumes:
      - ./:/webapps
    ports:
      - 5555:80
    networks:
      - base-network



networks:
  base-network:
    external: true
